feat: add concrete errors to public API
kurtisvg/cloud-sql-go-connector pull request #36
Opened 2021-08-09 14:51 UTC by enocom

This commit adds four concrete errors to the public API and ensures that
all returned errors are either instances of those concrete types OR are
wrapped by more descriptive errors.

The four error types are:

1. ClientError: for all errors that are the result of the client making
   a semantic error in their request

2. ServerError: for all the (uncommon) cases where the server returns
   data that is somehow and unexpectedly invalid.

3. APIError: for any errors that occurs when interacting with the SQL
   Admin API. These errors wrap the underlying
   google.golang.org/api/googleapi.Error types.

4. DialError: for any error that occurs when attempting to connect to a
   particular SQL instance.

By providing concrete errors or wrapping concrete errors, we allow our
clients to uses the errors.As API to possibly react differently to
errors coming out of the dialer.

2021-08-09 20:34 UTC, kurtisvg requested changes
High level thoughts:

`DialError` seems good. Should there be a high level error to capture anything during a refresh (e.g. `RefreshError`)? It seems like it might be useful between differentiating "the dial didn't' work" and "this refresh operation wasn't successful". 

I'm not sure I understand why `APIError` and `ServerError` are two different error types. Do I really care if the API returned a non 2xx code vs a bad response (or a response I couldn't parse)? Seems like differentiating isn't useful.

2021-08-11 16:47 UTC, enocom commented on errtypes/errors.go
> +// malformated, the SQL instance does not support the requested IP type, etc.)
Yeah, that makes sense. Let's use `ConfigError`. I'll update the docs here as well.

2021-08-11 17:15 UTC, enocom commented on errtypes/errors.go
> +func NewServerError(msg, cn string) *ServerError {
Fixed this.

2021-08-11 17:28 UTC, enocom commented
Could `ServerError` be renamed `RefreshError`?

2021-08-11 18:10 UTC, kurtisvg commented
RefreshError seems better than ServerError

2021-08-12 17:05 UTC, kurtisvg approved these changes

2021-08-12 17:05 UTC, kurtisvg commented on internal/cloudsql/refresh.go
> +		)
super-nit: I think it's generally cleaner to bias towards fewer lines over spreading the function call.
```suggestion
		msg := fmt.Sprintf("provided region was mismatched - got %s, want %s", inst.region, db.Region)
		return metadata{}, errtypes.NewRefreshError(msg, inst.String(), nil)
```

2021-08-12 18:49 UTC, merged